version: "3.5"

volumes:
  node-modules:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
      - 4004:4004
    command: nf start
    tty: true
    links:
      - mongo
    volumes:
      - .:/app
      - node-modules:/app/node_modules
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4005:4005
  #   command: npm run test
  #   links:
  #     - mongo
  #   volumes:
  #     - .:/app
  #     - node-modules:/app/node_modules
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
